packages: []

minimumReleaseAge: 0

allowBuilds:
  '@google/genai': false
  protobufjs: false

patchedDependencies:
  "@earendil-works/pi-coding-agent@0.84.2": "combined/pi-coding-agent.diff"
  "@earendil-works/pi-tui@0.84.2": "combined/pi-tui.diff"
