packages: []

minimumReleaseAge: 0

allowBuilds:
  '@google/genai': false
  esbuild: true
  protobufjs: false

patchedDependencies:
  "@earendil-works/pi-coding-agent@0.85.0": "combined/pi-coding-agent.diff"
  "@earendil-works/pi-tui@0.85.0": "combined/pi-tui.diff"
